### ISSUE TITLE
8

### ISSUE THREAD

**Issue by cccyb** [cccyb/blog#11]

**Comment by cccyb** [comment]
最近浏览自己的博客时发现，发现这个主题没有添加回到顶部特效组件，便想着应该不是很难吧，要不自己做一个加上去吧，于是就开始了，顺便开启前端网页特效的各种实现系列。

## 实现原理

回到顶部效果的载体可以是给一个`div`标签点击后通过`js`控制滚到顶部，也可以是一个`a`标签，通过点击锚点的默认回到顶部的原理来实现，但是后者最终的效果十分生硬，不美观，故这里采用前一种方法实现。
具体原理为：

- 给`div`添加背景，再添加`:hover`效果实现背景切换效果，这里可以自由发挥，不喜欢用背景图片的小伙伴也可以通过`css`实现各种效果。
- 然后将通过`position: fixed`将`div`固定到屏幕右下角，并设置`display: none`设置默认隐藏。
- 监听`window`的`scroll`事件，如果窗口卷过的高度`scrollTop`超过某个值，比如`200px`后，显示`div`，如果没有超过，这隐藏。
- 再给`div`添加点击事件，当点击`div`时通过`jquery`的动画将页面滚到顶部，这里使用了`jquery`是为了兼容性的考虑，也更加方便的添加动画效果。

## 代码实现

```html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta http-equiv="x-ua-compatible" content="ie=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>回到顶部</title>
  <link rel="stylesheet" href="reset.css">
  <link rel="stylesheet" href="index.css">
</head>
<body>
  <div class="box">
    <img src="images/tb_bg.jpg" alt="tb_bg">
  </div>
  <div id="back-top"></div>
  <script type="text/javascript" src="../lib/jquery-1.11.3.js"></script>
  <script type="text/javascript" src="index.js"></script>
</body>
</html>
```
这里使用了一张淘宝的长图来简单填充页面，同时引进了`jquery`方便开发。

```css
.box {
  width: 85%;
  margin: 0 auto;
}
.box img {
  width: 100%;
}
#back-top {
  display: none;
  width: 36px;
  height: 65px;
  position: fixed;
  right: 30px;
  bottom: 30px;
  background: url('images/gotop_rocket.png') no-repeat left top;
}
#back-top:hover {
  cursor: pointer;
  background: url('images/gotop_rocket.png') no-repeat left -65px;
}
```
这里将`back-topdiv`添加了`position: fixed`固定在屏幕右下角，同时背景使用了雪碧图和`background-postion`来优化性能。

```js
$(function() {
  $(window).scroll(function() { //只要窗口滚动,就触发下面代码
    var scrollTop = document.documentElement.scrollTop + document.body.scrollTop; //获取滚动后的高度
    if (scrollTop > 200) { //判断滚动后高度超过200px,就显示
      $("#back-top").fadeIn(400); //淡入
    } else {
      $("#back-top").stop().fadeOut(400); //如果返回或者没有超过,就淡出.必须加上stop()停止之前动画,否则会出现闪动
    }
  });
  $("#back-top").click(function() { //当点击标签的时候,使用animate在200毫秒的时间内,滚到顶部
    $("html,body").animate({
      scrollTop: "0px"
    }, 500);
  });
});
```
## 最终效果

滚动前：

![滚动前](http://obslj395t.bkt.clouddn.com/back-top-before.png)

向下浏览内容后：

![滚动后](http://obslj395t.bkt.clouddn.com/back-top-after.png)
